if(NOT ("$CMAKE_HOST_SYSTEM_NAME" STREQUAL "Linux" AND "$CMAKE_HOST_SYSTEM_PROCESSOR" STREQUAL "arm64"))
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR arm64)
endif()
set(CMAKE_C_COMPILER "aarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-g++")
set(CMAKE_Fortran_COMPILER "aarch64-linux-gnu-gfortran")