if(NOT ("$CMAKE_HOST_SYSTEM_NAME" STREQUAL "Darwin" AND "$CMAKE_HOST_SYSTEM_PROCESSOR" STREQUAL "arm64"))
    set(CMAKE_SYSTEM_NAME Darwin)
    set(CMAKE_SYSTEM_PROCESSOR arm64)
endif()
list(APPEND TOOLCHAINS ${DUCKDB_TOOLCHAINS})
message(WARNING ${TOOLCHAINS})
message(WARNING ${DUCKDB_TOOLCHAINS})
if("omp" IN_LIST TOOLCHAINS)
    message(WARNING "AA")
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-L/opt/homebrew/opt/libomp/lib")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "-L/opt/homebrew/opt/libomp/lib")
    set(CMAKE_MODULE_LINKER_FLAGS_INIT "-L/opt/homebrew/opt/libomp/lib")
    set(CMAKE_C_FLAGS_INIT "-I/opt/homebrew/opt/libomp/include")
    set(CMAKE_CPP_FLAGS_INIT "-I/opt/homebrew/opt/libomp/include")
    set(CMAKE_CXX_FLAGS_INIT "-I/opt/homebrew/opt/libomp/include")
endif()